config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos

  #scope :desc, order(name: :desc)
  #scope :asc, order(name: :asc)

  scope :sorted, -> { order(datetime: :asc) }
  scope :future, -> { where("datetime >=  ? ", Date.current) }
  scope :past, -> { where("datetime < ?", Date.current) }

  validates :user, presence: true

  validates :title, presence: true, length: {maximum: 255}

  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_event, except: [:index, :new, :create]

  before_action :password_guard!, only: [:show]
  skip_before_action :verify_authenticity_token

  after_action :verify_authorized, only: [:edit, :update, :destroy]

  def index
    @events = Event.sorted
  end

  def show
    authorize @event
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    # Болванка модели для формы добавления фотографии
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to events_url, notice: t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      render 'password_form'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label t('activerecord.attributes.event.title') %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label t('activerecord.attributes.event.address') %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label t('activerecord.attributes.event.datetime') %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label t('activerecord.attributes.event.description') %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label t('activerecord.attributes.event.pincode') %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('devise.shared.links.create'), class: 'btn btn-primary' %>
     <%= link_to t('devise.shared.links.back'), :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="buffer-both">
  <% if policy(Event).create? %>
    <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
  <% end %>
</div>

<div class="row buffer-bottom">
  <h2>Предстоящие</h2>
  <%= render partial: 'events/event', collection: @events.future %>
</div>
<div class="row buffer-bottom">
  <h2>Прошедшие</h2>
  <%= render partial: 'events/event', collection: @events.past.reverse %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<div class="col-md-6 buffer-top">
  <%= form_tag('', method: 'post') do |f| %>
    <div class="form-group">
      <%= label :pincode, 'Пин-код' %>
      <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
    </div>

    <div class="actions">
      <%= submit_tag t('activerecord.attributes.event.go'), :class => 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'На главную', events_path %>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-6">
      <%= content_tag 'div', '',
                      class: 'event-background',
                      style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>

            <h3><small><%= link_to @event.address,
                                   "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if policy(@event).edit? %>
            <div class="buffer-both">
              <%= link_to t('devise.registrations.edit.update'), edit_event_path(@event), class: 'btn btn-primary' %>
              <%= link_to t('devise.shared.links.delete'), event_path(@event), method: :delete,
                          data: {confirm: t('devise.registrations.edit.are_you_sure')}, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div id="map"
           data-address="<%= @event.address %>"
           style="width: 100%; height: 330px;">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
        <% if policy(@event).photo? %>
          <div class="event-photos-form">
            <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
          </div>
        <% end %>
      </div>
      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>
        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment).sorted_comment %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>

      </div>
      <div class="event-subscriptions">
        <% if @event.subscriptions.except(@new_subscription).count > 0 %>
          <h4>Пойдут:</h4>
          <div>
            <p>
              <%= render partial: 'subscriptions/subscription',
                         collection: @event.subscriptions.except(@new_subscription) %>
            </p>
          </div>
        <% end %>
      </div>
      <% if policy(@event).subscribe? && !@event.subscribers.include?(current_user) %>
        <div class="event-subscription-form">
          <h4>Я пойду:</h4>
          <div>
            <p>
              <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
              } %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>